apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
spec:
  ingressClassName: nginx
  defaultBackend:
    service:
      name: {{ .Release.Name }}
      port:
        number: {{ .Values.service.port }}
