replicaCount: 2
image:
  repository: sivoplyas/diplom-ssa
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  port: 80
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
