name: Docker Build
on:
  push:
    branches-ignore: ["main"]
  pull_request:
    branches-ignore: ["main"]
    types: [closed]

env:
    REGISTRY: https://index.docker.io/v1/
    IMAGE_NAME: test-ssa
    IMAGE_TAG: latest
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Log in to the Container registry
              uses: docker/login-action@v3.0.0
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}
      
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v3
              with:
                images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                tags: ${{ env.IMAGE_TAG }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v5.3.0
              with:
                context: .
                push: true
