name: Docker Deploy
on:
  push:
    tags:
      - 'v*'
env:
    REGISTRY: docker.io
    IMAGE_NAME: diplom-ssa
jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v1
              with:
                registry: ${{ env.REGISTRY }}
                username: ${{ secrets.DOCKER_USER }}
                password: ${{ secrets.DOCKER_TOKEN }}

#            - name: IMAGE VERSION
 #             run: |
  #              VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
      
            - name: Extract metadata (tags, labels) for Docker
              id: meta
              uses: docker/metadata-action@v2
              with:
                images: ${{ env.REGISTRY }}/${{ github.ref_name }}
            
            - name: Build and push Docker image
              uses: docker/build-push-action@v2
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKER_USER }}/${{ env.IMAGE_NAME }}:${{ github.ref_name }}
