name: Auto Tagging

on:
  push:
    branches:
      - main

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: Get Latest Version
        id: get_version
        run: |
          git fetch --tags
          git tag --sort=-creatordate | head -n 1 | sed 's/^v//'          
      
      - name: Bump Version
        id: bump_version
        run: |
          # Determine the new version based on commit messages
          NEW_VERSION=$(node scripts/get-new-version.js ${{ github.event.head_commit.message }})
          echo "New version: $NEW_VERSION"
          echo "::set-output name=new_version::$NEW_VERSION"          

      - name: Create Tag
        run: |
          git tag "v${{ steps.bump_version.outputs.new_version }}"
          git push origin "v${{ steps.bump_version.outputs.new_version }}"   
